workflows:
  android-build:
    name: Android Build
    environment:
      node: latest
      java: 17
    scripts:
      - name: Build Android
        script: |
          echo "=== INICIANDO BUILD ==="
          
          # Instalar dependências
          npm install
          npm install @capacitor/core @capacitor/android
          
          # Build do web app
          npm run build
          
          # Configurar Capacitor
          npx cap init KizombaTok com.kizombatok.app
          npx cap add android
          npx cap copy
          
          # Compilar APK
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - "android/app/build/outputs/**/*.apk"
