workflows:
  android-build:
    name: Android Build
    environment:
      node: latest
    scripts:
      - npm install
      - npm install @capacitor/core @capacitor/cli @capacitor/android
      - npm run build
      - |
        if [ ! -f capacitor.config.json ]; then
          echo '{
            "appId": "com.kizombatok.app",
            "appName": "KizombaTok",
            "webDir": "dist",
            "bundledWebRuntime": false
          }' > capacitor.config.json
        fi
      - npx cap add android
      - npx cap copy
      - cd android
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
