workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.kizombatok.angolavibe"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - 200ricardocolino@gmail.com # Altera para o teu e-mail nas definições do Codemagic
