workflows:
  android-capacitor:
    name: Android Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 21
      groups:
        - google_play
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          # Usar o gradle do sistema para evitar erro de jar corrompido no wrapper
          gradle assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
