workflows:
  android-build:
    name: Android Build
    environment:
      node: latest  # Se você precisa de Node para algo específico
      java: 17      # Use a versão do Java compatível com seu projeto
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.m2/repository
    scripts:
      - name: Verificar versão do Java
        script: |
          echo "=== VERIFICANDO VERSÃO DO JAVA ==="
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
      
      - name: Verificar estrutura do projeto
        script: |
          echo "=== ESTRUTURA DO PROJETO ==="
          ls -la
          echo "=== DIRETÓRIO ANDROID ==="
          if [ -d "android" ]; then
            cd android
            ls -la
            cd ..
          else
            echo "Diretório android não encontrado na raiz"
          fi
      
      - name: Compilar Android
        script: |
          echo "=== COMPILANDO PROJETO ANDROID ==="
          
          # Verificar se estamos no diretório correto
          # Se seu projeto Android está na raiz
          if [ -f "gradlew" ]; then
            echo "Encontrado gradlew na raiz"
            chmod +x gradlew
            ./gradlew assembleRelease
          # Se está em uma subpasta android
          elif [ -d "android" ] && [ -f "android/gradlew" ]; then
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease
            cd ..
          # Se está em uma subpasta app
          elif [ -d "app" ] && [ -f "gradlew" ]; then
            echo "Encontrado gradlew na raiz com pasta app"
            chmod +x gradlew
            ./gradlew assembleRelease
          else
            echo "Arquivo gradlew não encontrado. Procurando em subdiretórios..."
            find . -name "gradlew" -type f
          fi
      
      - name: Listar APKs gerados
        script: |
          echo "=== APKs GERADOS ==="
          find . -name "*.apk" -type f | xargs ls -la
    artifacts:
      - app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.apk
      - **/*.apk
