workflows:
  android-build:
    name: Android Build
    environment:
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.m2/repository
    scripts:
      - name: Verificar estrutura do projeto
        script: |
          echo "=== DIAGNÓSTICO DO PROJETO ==="
          echo "Diretório atual: $(pwd)"
          echo "\n=== LISTANDO ARQUIVOS NA RAIZ ==="
          ls -la
          
          echo "\n=== PROCURANDO ARQUIVOS GRADLE ==="
          find . -name "build.gradle" -type f | head -10
          find . -name "gradlew" -type f | head -5
          
          echo "\n=== VERIFICANDO PASTAS COMUNS ==="
          if [ -d "app" ]; then
            echo "\nConteúdo da pasta app:"
            ls -la app/
          fi
          
          if [ -d "android" ]; then
            echo "\nConteúdo da pasta android:"
            ls -la android/
          fi
      
      - name: Compilar APK
        script: |
          echo "=== COMPILANDO APK ==="
          
          if [ -f "gradlew" ]; then
            echo "Encontrado gradlew na raiz"
            chmod +x gradlew
            ./gradlew assembleRelease
          elif [ -d "android" ] && [ -f "android/gradlew" ]; then
            echo "Encontrado gradlew na pasta android"
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease
            cd ..
          elif [ -d "app" ] && [ -f "gradlew" ]; then
            echo "Encontrado gradlew na raiz com pasta app"
            chmod +x gradlew
            ./gradlew assembleRelease
          else
            echo "ERRO: Não foi possível encontrar o projeto Android"
            exit 1
          fi
      
      - name: Listar APKs gerados
        script: |
          echo "=== APKs GERADOS ==="
          find . -name "*.apk" -type f | while read apk; do
            ls -la "$apk"
          done
    artifacts:
      - "app/build/outputs/**/*.apk"
      - "android/app/build/outputs/**/*.apk"
      - "**/*.apk"
